name: OpenSSF Scorecard

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          publish_results: true

      - name: Upload Scorecard Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
